spring.application.name=user-management-system

#MySQL Database Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/demo
spring.datasource.username=root
spring.datasource.password=123456

#hibernate Configuration
spring.jpa.show-sql=true

